### ISSUE TITLE
Issues with published views, among other things. 

### ISSUE THREAD

**Issue by TheZachh** [WebDevEtc/BlogEtc#2] opened 2018-12-04 20:37 UTC
Hello, 

First I wanted to say that I really appreciate what this package does out of the box, but I have several issues I need to point out. I'm not sure if it was built this way intentionally or if something went wrong with my copy. Here goes: 

**Issue 1:** When publishing the views, there are no assets that appear for use in the public directory except for a CSS file. Instead, I get a horrible set of front-end views inside the Resources/Views/Vendor/blogetc folder. 

I call them horrible because they are nearly impossible to work with in an efficient way. It only publishes the front end views, which are made up of layers and layers of nested components and includes which are mostly unnecessary and call back to the source code instead of allowing my changes to override them.

 I have to go into the source code and remove all of the excess columns and layout inconsistencies. 

This causes the views to look warped and defy the master layout, even when I put in my own layout. Not to mention that **all of my changes will revert in a package update**, so I'd rather not have to mod the source code. 

Modifying the views also has almost no effect because everything is included and referenced back to the package which in turn has more and more nested layers and components that you can't manipulate without going into some file, finding out that the view is just composed of more includes that you have to track down in the source. 

**Issue 2:** There are no publishable assets regarding the admin views. I have to go into the source and modify it there, which is also layered and nested several facets of includes and thus, the CSS does not render. I can see all the text in my view, but there are no publishable files for the view so I can't add them to the resources. 

**Issue 4:** There are no obvious navigational components. I had to again go into the source and look at the routes file which thankfully included comments. 

**Issue 5:** Several components will have improper classifications, such as the post edit button which contained both a **"pull-right" (deprecated from Bootstrap 3)** and a **float-right (BS4)** right the pull-right. 

Even after removing and reinstalling the package, the **views do not render properly and do not publish usable assets **, but all of the blog functionality works fine. 

I do not mean to sound like I'm bashing the package, it works in functionality but requires several modifications to the source to prevent middleware clashes, fix invalid code and the layout problems. 

Is there something I am doing wrong? Please let me know if you need more information from me as well. 

Thank you :)

**Comment by WebDevEtc** [comment] 2018-12-05 08:59
Hi,
Thanks for using my package & the feedback.

I'll try and address your main points. You made quite a few points, so this reply will inevitably be a bit long :) 

_If you don't have time to read it all - this package focuses on the backend stuff, and was written with the assumption that you'd provide your own custom layout, and  most of the points you mentioned about unable to edit view files can be resolved by just editing views in your main views directory: `/resources/views/blogetc` (or make a directory called `blogetc_admin` there for the admin views - this isn't in the docs, I will update them) - not editing in composer's /vendor/webdevetc/blogetc/. Files in there won't get overwritten by package updates or vendor:publish._

BTW, I definitely focused more on the internal and backend stuff, as I assumed (perhaps incorrectly assumed!) that most people who want to add a blog to a Laravel app already have a 'main' app (with it's own design/layout and probably own `layouts/app.blade.php` layout with its own css)) and wanted to add a small company blog to their site, so I assumed that people would almost always want to customise the blog's looks (i.e. the HTML in the blade files), so I didn't really concentrate on the frontend. I just tried to get something generic looking, if a bit basic, that works with the default Laravel install. 

But you're right that by default it could provide better options. Some of your points confuse me a bit (talking about columns and `Agent::isAdmin()` which aren't part of my package!) but I'll get to them in a bit :)

> Issue 1: When publishing the views, there are no assets that appear for use in the public directory except for a CSS file

This is intentional. I assume you're going to make it use your current theme/layout. It assumes that you have done `php artisan make:auth` (so it can `@extend("layouts.app")` , which itself uses the default CSS: ` <link href="{{ asset('css/app.css') }}" rel="stylesheet">` however I assume that you'd change this to your site's own frontend code. 

I just did a test install (I needed to double check everything before I reply), this is how it looks (I have only modified the .env for DB settings, added the `canManageBlogEtcPosts()` method to my User model). It doesn't really use any other assets, just the default laravel stuff (via `layouts/app.blade.php`)

![image](https://user-images.githubusercontent.com/42039233/49500551-dc3be480-f868-11e8-9161-a45e8b620249.png)

![image](https://user-images.githubusercontent.com/42039233/49500560-e1009880-f868-11e8-94aa-2511a1529a8b.png)


> It only publishes the front end views

What else would you prefer were published? 

> I have to go into the source code and remove all of the excess columns and layout inconsistencies.

I don't really use columns in the default theme. There are some references to `col-sm-12`, but with bootstrap that is a full width column (so actually, I'm not sure why I added that class - I'll remove it in next major update). (Here are all the cols: https://imgur.com/a/MG8qvYH )

> I have to go into the source code and remove all of the excess columns and layout inconsistencies.

By source code, do you mean `/vendor/webdevetc/blogetc/` ? Please don't do this! :) If this is what you meant, then yes if you update the package then your changes will get overwritten.

> Not to mention that all of my changes will revert in a package update, so I'd rather not have to mod the source code.

Not if you edit the files in `/resources/views/vendor/blogetc/` ! They won't get overwritten!

If you want to edit the admin blade files, then create a dir: `/resources/views/vendor/blogetc_admin/` and put the files in there. I will add this to the docs to explain, as I didn't include this.

BTW, as all references in the blade files uses two colons (for example: `  return view("blogetc::index", [   ...      ]);`) then first it will look in `/resources/views/vendor/blogetc/`, if nothing is found then it'll default to `vendor/webdevetc/blogetc/src/Views/`.

In addition, when you do `vendor publish`, it won't overwrite the files. I just tested this to confirm - I installed blogetc, edited a file (resources/views/vendor/blogetc/index.blade.php), then removed the package, reinstalled it, re-run vendor:publish, to confirm that the file was no overwritten! (It wasn't - my changes were still there).

> Modifying the views also has almost no effect because everything is included and referenced back to the package which in turn has more and more nested layers and components that you can't manipulate without going into some file, finding out that the view is just composed of more includes that you have to track down in the source.

There are only really two main files: `resources/views/vendor/blogetc/index.blade.php` and `resources/views/vendor/blogetc/single_post.blade.php`. You can put all the code in those and ignore any other files, if you prefer that way. 

But you're right, there are a few too many files and it could be better organised. This project was extracted from some other websites of mine, I should have made more time making them more generic and easier to use.

> Issue 2: There are no publishable assets regarding the admin views. I have to go into the source and modify it there

See above :) Just create the views as required in `/resources/views/blogetc_admin/`.
This is set up in the service provider:

```
    /**
     * Register services.
     *
     * @return void
     */
    public function register()
    {

        // for the admin backend views ( view("blogetc_admin::BLADEFILE") )
        $this->loadViewsFrom(__DIR__ . "/Views/blogetc_admin", 'blogetc_admin');

        // for public facing views (view("blogetc::BLADEFILE")):
        // if you do the vendor:publish, these will be copied to /resources/views/vendor/blogetc anyway
        $this->loadViewsFrom(__DIR__ . "/Views/blogetc", 'blogetc');
    }
```

I've made a lot of assumptions when creating this package, but I didn't really think that people would be too bothered about modifying the admin pages. I've worked with many wordpress sites in the past - I can't ever recall seeing a custom admin backend, but of course never the default WP theme for the public facing pages.

> Issue 3: I had to go in and edit several parts of the source code because the isAdmin middleware 

There is no `isAdmin` middleware in my package. Only this: https://github.com/WebDevEtc/BlogEtc/blob/master/src/Middleware/UserCanManageBlogPosts.php 

> I changed public static function to public function and edited all of the calls for Agent::isAdmin() to $agent = auth()->user() if($agent->isAdmin() and it resolved the problem or conflict.

This isn't part of my package (I have no references to agents or isAdmin). 

For authorisation I check the user model for a method `canManageBlogEtcPosts()` - this isn't the best way I could have done it, but this was intended for a small company blog on top of a bigger app. Adding one simple method on a user (which I assumed would mostly be hard coded to a specific user id - but obviously not all uses are going to be like this...) seemed like the easiest way to do this, rather than gates or something else.

> I changed public static function to public function

I don't really use static methods in this package (there are some in a helper class). 

> Issue 4: There are no obvious navigational components. I had to again go into the source and look at the routes file which thankfully included comments.

What would be useful?

There are a few notes on https://webdevetc.com/laravel/packages/blogetc-blog-system-for-your-laravel-app/help-documentation/laravel-blog-package-blogetc#guide_to_views 

![image](https://user-images.githubusercontent.com/42039233/49500530-d1814f80-f868-11e8-8adf-37dac1f15f0f.png)

> Issue 5: Several components will have improper classifications, such as the post edit button which contained both a "pull-right" (deprecated from Bootstrap 3) and a float-right (BS4) right the pull-right.

You're right :) I think that my thinking was probably so it was compatible with both versions of bootstrap. A lot of sites still use BS3. Obviously if your theme isn't using bootstrap then both are useless! 

I only really use them in the admin panel, with 2 references on the public facing parts (one for an edit button, one for the comment's created at time)
![image](https://user-images.githubusercontent.com/42039233/49500808-70a64700-f869-11e8-97b7-8ae6fee6fd19.png)



When I get some free time I do plan to clean it all up, make it more compatible. But to be honest, now that it has some installs and people are using this I'm a bit concerned that even if I update to v4 (next major version) and I make it clear on the docs that this might break things that people might update and it could mess up their existing site. Maybe I should add themes, set the current files as a theme for legacy installs and other themes for newer installs.

>I do not mean to sound like I'm bashing the package, it works in functionality but requires several modifications to the source to prevent middleware clashes, fix invalid code and the layout problems.

No worries :) I'm happy that there is feedback.  There are some good valid points you made (some which confuse me! like isAdmin() etc), but I've designed the package so you can easily (in my head it seems easy, but maybe it isn't really!) customise the blade files. 

BTW, what sort of site do you use it for? Is it an existing web app (or something similar) that you wanted to add a blog to?

**Comment by TheZachh** [comment] 2018-12-05 23:12
First of all, I want to say a big **thank you** for taking the time to reply and in a way that really hits on all of my original questions/issues. 

Now I understand more about your reasoning behind the views. I basically imported the BlogETC into my already existing app with Composer and attempted to publish views, etc. and that where I started a "deep dive" into finding out why things were not looking the way I thought they were supposed to. 

Secondly, I need to apologize for my confusion -- it seems I had mistakenly dragged a folder from another package I was working with into the BlogETC folder and thats why I thought the middleware was coming from it (the package I was using was a deprecated ticket system).

So I'll strike those points out from the original post for clarity sake.  

To answer your question, yes it was put into an existing app (which I should have demoed on a test server first). But now that you've also explained the views, I will attempt to drag them into the primary directory. 

For context, here are some screenshots. Some of my master layout did work, but some things are somehow turned white, etc. 

![blogetc_viewpost](https://user-images.githubusercontent.com/19249281/49550340-dff35980-f8b0-11e8-826f-cee202098a62.PNG)
![blogetc_index](https://user-images.githubusercontent.com/19249281/49550342-e08bf000-f8b0-11e8-9d9c-794a93002177.PNG)
![blogetc_admin](https://user-images.githubusercontent.com/19249281/49550343-e08bf000-f8b0-11e8-8057-6f914b7dc3a0.PNG)
![blogetc_footer](https://user-images.githubusercontent.com/19249281/49550344-e08bf000-f8b0-11e8-8c45-ccb9f68c68fb.PNG)

**Closed as completed** 2018-12-07 00:11 UTC
